# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lag-suc # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region}
  stage: ${opt:stage}

functions:
  LoanCreated:
    handler: src/loan-created/handler.handleLoanCreated
    events:
      - sns:
          arn: ${cf:lag-awh-${opt:stage}.LoanCreatedTopicArn}
    environment:
      UserCacheTableName: ${self:custom.TableNames.userCacheTable}
      LoanCacheTableName: ${self:custom.TableNames.loanCacheTable}
      UsersQueueName: ''
      UsersQueueOwner: ''
  LoanRenewed:
    handler: src/loan-renewed/handler.handle
    events:
      - sns:
          arn: ${cf:lag-awh-${opt:stage}.LoanRenewedTopicArn}
    environment:
      UserCacheTableName: ${self:custom.TableNames.userCacheTable}
      LoanCacheTableName: ${self:custom.TableNames.loanCacheTable}
      UsersQueueName: ''
      UsersQueueOwner: ''

resources:
  Resources:
    userCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.TableNames.userCacheTable}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    loanCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.TableNames.loanCacheTable}
        AttributeDefinitions:
          - AttributeName: loan_id
            AttributeType: S
        KeySchema:
          - AttributeName: loan_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5    
  
  Outputs:
    UserCacheTableArn:
      Description: Arn of User Cache Table
      Value: ${self:custom.TableArns.userCacheTable}
      Export:
        Name: ${self:service}:${opt:stage}:UserCacheTableArn
    LoanCacheTableArn:
      Description: Arn of Loan Cache Table
      Value: ${self:custom.TableArns.loanCacheTable}
      Export:
        Name: ${self:service}:${opt:stage}:LoanCacheTableArn

custom:
  TableArns:
    userCacheTable:
      "Fn::GetAtt": [userCacheTable, Arn]
    loanCacheTable:
      "Fn::GetAtt": [loanCacheTable, Arn]
  TableNames:
    userCacheTable: ${self:service}-userCacheTable-${opt:stage}
    loanCacheTable: ${self:service}-loanCacheTable-${opt:stage}

